In [2]:
x = 1
y = 2
x+y

3

### To jest przyklad markdown

To jest lista

* a
* b

To jest fragment kodu:

```python
    x = 1
    y = 2
    x+y
```

In [2]:
import numpy as np

In [4]:
a = [1,2,3] * 500000
b = np.array(a)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


array([3, 6, 9, 3, 6, 9, 3, 6, 9])

In [6]:
%%timeit -n1
[i ** 2 for i in a]

6.44 µs ± 965 ns per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
%%timeit
b ** 2

921 ns ± 26.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
x = [[1,2], [2,3], [3,4]]
a = np.array(x)
a

array([[1, 2],
       [2, 3],
       [3, 4]])

In [11]:
a*5

array([[ 5, 10],
       [10, 15],
       [15, 20]])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x = np.arange(25)
print(x)
x = x.reshape((5,5))
x.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


(5, 5)

In [15]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
m = []
for i in range(1,101):
    k = i**2
    m.append(k)

M = np.array(m)
M = M.reshape((10,10))
M

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])